### ISSUE TITLE
curl request

### ISSUE THREAD

**Issue by hanwencheng** [zhao-han/anti-qqphishing#1]
is the main idea to use curl to send post request to these phishing website?
if use one ip send so much request, these website could easily block this ip, how to deal with that?

**Comment by h4n0** [comment]
Good question.
I'm still not trying this in practice because recently the phishing websites do not appear as frequently as usual. 
But I don't think I'll use my own laptop to run this script. Maybe using Tor is a good solution of this.

**Comment by hanwencheng** [comment]
Wow, sounds cooooool,
I just check Tor, it is really interesting, but I don't know how to use it yet.

**Comment by h4n0** [comment]
Just install it and you can start right on. It's a perfect system that even its creator and FBI can't hack.
